# Site settings
title: Chengji Xu' Homepage
description:
url: "xuchengji.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Chengji Xu
  bio      : 
  email    : xuchj@sit.edu.cn
  twitter  : 

#SEO settings
logo:  # Site logo URL
twitter_username:  # Twitter username
facebook:
    app_id:  # App ID
    publisher:  # URL of the Facebook page
    admins:  # Facebook user ID that manages the page

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed
